version: '3.8'

services:
  lighthousedevcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      # Docker
      - ~/.docker:/node/.docker
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      # On Linux and OSX, a symlink /mnt/ssh <-> ~/.ssh is
      # created in the container. On Windows, files are copied
      # from /mnt/ssh to ~/.ssh to fix permissions.
      - ~/.ssh:/mnt/ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/home/node/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - audit_net

networks:
  audit_net:
